<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class EquipementSeeder extends Seeder
{
    public function run()
    {
        DB::table('equipements')->insert([
            [
                'nom' => 'Onduleurs',
                'marque' => 'OPTI UPS',
                'description' => 'Appareil de secours électrique pour les coupures de courant (protection réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleurs.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Onduleur',
                'marque' => 'MERCURY',
                'description' => 'Alimentation de secours pour équipements électroniques réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleur_mercury.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Onduleur',
                'marque' => 'EATON',
                'description' => 'Appareil UPS pour la protection de données en cas de coupure (réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleur_eaton.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Brasseurs',
                'marque' => 'SMC',
                'description' => 'Équipement de gestion de câblage dans les baies réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/brasseurs.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Répéteur',
                'marque' => 'WPS',
                'description' => 'Appareil permettant d’étendre la portée du signal Wi-Fi.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/repeteur.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ODF',
                'marque' => 'inconnue',
                'description' => 'Organisateur de fibres optiques (ODF).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/odf.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ONT',
                'marque' => 'HUAWEI',
                'description' => 'Terminal réseau optique (ONT) de marque HUAWEI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ont.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DOM',
                'marque' => 'HIKVISION',
                'description' => 'Dispositif de sécurité HIKVISION.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dom_hikvision.jpeg',
                'categorie_id' => 3,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rouleau câble Ethernet',
                'marque' => 'inconnue',
                'description' => 'Rouleau de câble réseau Ethernet.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/rouleau_cable_ethernet.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Souffleur',
                'marque' => 'WORXPLEX',
                'description' => 'Souffleur pour le nettoyage extérieur et chantiers télécom.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/souffleur_worxplex.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Scie à Métaux',
                'marque' => 'inconnue',
                'description' => 'Scie pour couper le métal (travaux de chantier télécom).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/scie_a_metaux.jpeg',
                'categorie_id' => 2,
                'quantite' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',
                'marque' => 'GRANDSTREAM',
                'description' => 'Téléphone fixe de marque GRANDSTREAM.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_grandstream.jpeg',
                'categorie_id' => 4,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Marteau Piqueur',
                'marque' => 'TITAN',
                'description' => 'Marteau piqueur de marque TITAN (travaux de chantier).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/marteau_piqueur_titan.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ONT HUAWEI',
                'marque' => 'HUAWEI',
                'description' => 'Terminal réseau optique HUAWEI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ont_huawei.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'MEDIA Converter',
                'marque' => 'NetPro',
                'description' => 'Convertisseur média NetPro.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/media_converter_netpro.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupleur LC Bleue',
                'marque' => 'inconnue',
                'description' => 'Coupleur LC de couleur bleue (fibre optique).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/coupleur_lc_bleue.jpeg',
                'categorie_id' => 1,
                'quantite' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteur Fibre',
                'marque' => 'inconnue',
                'description' => 'Connecteur pour fibre optique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteur_fibre.jpeg',
                'categorie_id' => 1,
                'quantite' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupleur LC Vert',
                'marque' => 'inconnue',
                'description' => 'Coupleur LC de couleur verte (fibre optique).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/coupleur_lc_vert.jpeg',
                'categorie_id' => 1,
                'quantite' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur Echolife',
                'marque' => 'inconnue',
                'description' => 'Routeur Echolife pour réseau informatique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_echolife.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Fibre Transparente',
                'marque' => 'inconnue',
                'description' => 'Fibre optique transparente.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/fibre_transparente.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boite de Dérivation',
                'marque' => 'inconnue',
                'description' => 'Boite pour dérivation fibre optique / réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/boite_derivation.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Caméra HILOOK',
                'marque' => 'HILOOK',
                'description' => 'Caméra de surveillance HILOOK.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/camera_hilook.jpeg',
                'categorie_id' => 3,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',
                'marque' => 'ALCATEL',
                'description' => 'Téléphone fixe de marque ALCATEL.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_alcatel.jpeg',
                'categorie_id' => 4,
                'quantite' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Serveur OPTI UPS',
                'marque' => 'inconnue',
                'description' => 'Serveur avec alimentation UPS OPTI (réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/serveur_opti_ups.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Malette d’équipement',
                'marque' => 'inconnue',
                'description' => 'Malette contenant divers équipements nécessaires pour intervention terrain.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/malette_equipement.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Embase de Prise RJ45',
                'marque' => 'inconnue',
                'description' => 'Embase pour prise réseau RJ45.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/embase_prise_rj45.jpeg',
                'categorie_id' => 1,
                'quantite' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plaque Frontale',
                'marque' => 'inconnue',
                'description' => 'Plaque frontale pour prise réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/plaque_frontale.jpeg',
                'categorie_id' => 1,
                'quantite' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince Optique',
                'marque' => 'inconnue',
                'description' => 'Pince pour manipulation de fibre optique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_optique.jpeg',
                'categorie_id' => 2,
                'quantite' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Testeur RJ45 RJ11',
                'marque' => 'inconnue',
                'description' => 'Testeur pour câbles RJ45 et RJ11.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/testeur_rj45_rj11.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Perceuse T.I.P',
                'marque' => 'inconnue',
                'description' => 'Perceuse électrique T.I.P (travaux de pose réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/perceuse_tip.jpg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Multimètre',
                'marque' => 'ING-CO',
                'description' => 'Multimètre de marque ING-CO (tests réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/multimetre_ingco.jpg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câbles Ethernet Pré sertis',
                'marque' => 'inconnue',
                'description' => 'Câbles Ethernet déjà sertis prêts à l’emploi.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cables_ethernet_presertis.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BNC',
                'marque' => 'inconnue',
                'description' => 'Connecteurs BNC pour câblage.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bnc.jpeg',
                'categorie_id' => 1,
                'quantite' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur CISCO',
                'marque' => 'CISCO',
                'description' => 'Routeur réseau CISCO.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_cisco.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe THOSON',
                'marque' => 'THOSON',
                'description' => 'Téléphone fixe de marque THOSON.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_thoson.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Surface BOX',
                'marque' => 'inconnue',
                'description' => 'Surface BOX pour installation technique réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/surface_box.jpg',
                'categorie_id' => 1,
                'quantite' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',
                'marque' => 'Panasonic',
                'description' => 'Téléphone fixe Panasonic.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_panasonic.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Testeur Câbles Ethernet',
                'marque' => 'NOYAFA',
                'description' => 'Testeur de câbles Ethernet de marque NOYAFA.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/testeur_cables_ethernet_noyafa.jpg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DVR',
                'marque' => 'HIKVISION',
                'description' => 'Enregistreur vidéo numérique HIKVISION (surveillance).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dvr_hikvision.jpg',
                'categorie_id' => 3,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DVR',
                'marque' => 'AUSNO',
                'description' => 'Enregistreur vidéo numérique AUSNO (surveillance).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dvr_ausno.jpg',
                'categorie_id' => 3,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Détecteur Incendie',
                'marque' => 'inconnue',
                'description' => 'Détecteur d’incendie pour sécurité.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/detecteur_incendie.jpeg',
                'categorie_id' => 3,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone/PBX',
                'marque' => 'inconnue',
                'description' => 'Système téléphonique PBX.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_pbx.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Fer à Souder',
                'marque' => 'inconnue',
                'description' => 'Fer à souder pour travaux électroniques et réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/fer_a_souder.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tie',
                'marque' => 'inconnue',
                'description' => 'Serre-câbles (Tie) pour gestion des câbles réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/tie.jpeg',
                'categorie_id' => 1,
                'quantite' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince à Sertir Bleue',
                'marque' => 'inconnue',
                'description' => 'Pince à sertir de couleur bleue (câblage réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_a_sertir_bleue.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince à Sertir Verte',
                'marque' => 'inconnue',
                'description' => 'Pince à sertir de couleur verte (câblage réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_a_sertir_verte.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Interrupteur YAKI',
                'marque' => 'inconnue',
                'description' => 'Interrupteur de marque YAKI (installation réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/interrupteur_yaki.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur D-Link',
                'marque' => 'D-Link',
                'description' => 'Routeur réseau de marque D-Link.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_dlink.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Switch HIKVISION',
                'marque' => 'HIKVISION',
                'description' => 'Switch réseau HIKVISION.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/switch_hikvision.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bande de Signalisation/Délimiteur',
                'marque' => 'inconnue',
                'description' => 'Bande pour signalisation et délimitation sur chantier.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bande_signalisation.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Poulie',
                'marque' => 'inconnue',
                'description' => 'Poulie pour levage ou guidage de câbles (chantier).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/poulie.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur HDD 1TO',
                'marque' => 'inconnue',
                'description' => 'Disque dur HDD de 1 To (serveurs réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_hdd_1to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Prolongateur HDMI RX',
                'marque' => 'inconnue',
                'description' => 'Prolongateur HDMI RX pour transmission vidéo réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/prolongateur_hdmi_rx.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteurs BNC',
                'marque' => 'inconnue',
                'description' => 'Connecteurs BNC pour câblage vidéo/réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteurs_bnc.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteur RJ45',
                'marque' => 'inconnue',
                'description' => 'Connecteur réseau RJ45.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteur_rj45.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble Coaxial UTP',
                'marque' => 'inconnue',
                'description' => 'Câble coaxial UTP pour transmission de données.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_coaxial_utp.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble BNC',
                'marque' => 'inconnue',
                'description' => 'Câble avec connecteur BNC.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_bnc.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur SATA 1TO',
                'marque' => 'TOSHIBA',
                'description' => 'Disque dur SATA 1 To de marque TOSHIBA (serveurs).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_sata_toshiba.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur SAS 2 TO',
                'marque' => 'inconnue',
                'description' => 'Disque dur SAS de 2 To (serveurs réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_sas_2to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur Pipeline HD 2 TO',
                'marque' => 'inconnue',
                'description' => 'Disque dur Pipeline HD de 2 To (serveurs).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_pipeline_hd_2to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Caméra EncroVision',
                'marque' => 'inconnue',
                'description' => 'Caméra de marque EncroVision (surveillance).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/camera_encrovision.jpeg',
                'categorie_id' => 3,
                'quantite' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connect Assessories',
                'marque' => 'inconnue',
                'description' => 'Accessoires divers de connexion réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connect_assessories.jpeg',
                'categorie_id' => 1,
                'quantite' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble 350.024.373',
                'marque' => 'inconnue',
                'description' => 'Câble référence 350.024.373 (réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_350_024_373.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble 350.024.336',
                'marque' => 'inconnue',
                'description' => 'Câble référence 350.024.336 (réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_350_024_336.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble (CLIP)',
                'marque' => 'inconnue',
                'description' => 'Câble type CLIP (réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_clip.jpeg',
                'categorie_id' => 1,
                'quantite' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Échelle rouge',
                'marque' => 'inconnue',
                'description' => 'Échelle en aluminium ou métal peint en rouge, utilisée pour les accès en hauteur (chantier).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/echelle_rouge.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rallonge',
                'marque' => 'Ingelec',
                'description' => 'Rallonge électrique de marque Ingelec (chantier/réseau).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/rallonge_ingelect.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'PABX TC-3000K IKE',
                'marque' => 'inconnue',
                'description' => 'Système PABX TC-3000K de marque IKE.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pabx_tc3000k_ike.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
