<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class EquipementSeeder extends Seeder
{
    public function run()
    {
        DB::table('equipements')->insert([
            [
                'nom' => 'La Fontaine Bonbonne',
                'marque' => 'CWAY',
                'description' => 'Distributeur d’eau avec bonbonne pour rafraîchissement en bureau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/la_fontaine_bonbonne.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Onduleurs',

                'marque' => 'OPTI UPS',
                'description' => 'Appareil de secours électrique pour les coupures de courant.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleurs.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Imprimante',

                'marque' => 'HP',
                'description' => 'Imprimante standard pour les impressions bureautiques.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/imprimante.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Régulateur',

                'marque' => 'Roche',
                'description' => 'Stabilisateur de tension pour matériel électrique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/regulateur.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Roll Up',

                'marque' => 'inconnue',
                'description' => 'Support d’affichage publicitaire portatif.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/roll_up.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Imprimante 3 en 1',

                'marque' => 'Olivetti',
                'description' => 'Imprimante multifonction : impression, scan et copie.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/imprimante_3_en_1.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bureau Armoire',

                'marque' => 'inconnue',
                'description' => 'Mobilier de rangement intégré au bureau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bureau_armoire.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Relieuse',

                'marque' => 'Buyor',
                'description' => 'Appareil pour relier des documents.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/relieuse.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Paper Cutter',

                'marque' => 'inconnue',
                'description' => 'Massicot de coupe pour papiers et documents.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/paper_cutter.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Imprimante 3 en 1',

                'marque' => 'HP',
                'description' => 'Imprimante multifonction HP.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/imprimante_3_en_1_hp.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Table Bureautique/Stagiaire',

                'marque' => 'inconnue',
                'description' => 'Table de travail destinée aux stagiaires ou usage bureautique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/table_bureautique_stagiaire.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bureau secrétariat',

                'marque' => 'inconnue',
                'description' => 'Bureau utilisé par le personnel de secrétariat.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bureau_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bureau Communication',

                'marque' => 'inconnue',
                'description' => 'Bureau attribué au service de communication.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bureau_communication.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Vidéo Projecteur',

                'marque' => 'NEC',
                'description' => 'Appareil de projection vidéo pour présentations.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/video_projecteur.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Range Cachets',

                'marque' => 'inconnue',
                'description' => 'Support ou casier pour rangement des cachets.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/range_cachets.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Micro Panasonic',

                'marque' => 'Panasonic',
                'description' => 'Microphone de bureau pour usage professionnel.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/micro_panasonic.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Ecran Bureautique/Secrétariat',

                'marque' => 'DELL',
                'description' => 'Écran informatique pour travail de bureau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ecran_bureautique_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Souris/ Secrétariat',

                'marque' => 'inconnue',
                'description' => 'Souris informatique pour poste de secrétariat.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/souris_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier Bureautique / Secrétariat',

                'marque' => 'HP',
                'description' => 'Clavier HP pour usage bureautique au secrétariat.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_bureautique_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Unité Centrale / Secrétariat',

                'marque' => 'HP',
                'description' => 'Unité centrale HP pour bureau de secrétariat.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/unite_centrale_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tiroir/ Secrétariat',

                'marque' => 'inconnue',
                'description' => 'Tiroir de rangement pour poste de secrétariat.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/tiroir_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Attache-Lettre/ Secrétariat',

                'marque' => 'inconnue',
                'description' => 'Accessoire pour maintenir ensemble des documents papier.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/attache_lettre_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Barre Décorateur',

                'marque' => 'inconnue',
                'description' => 'Barre utilisée à des fins décoratives dans un bureau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/barre_decorateur.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bureau/ Secrétariat',

                'marque' => 'inconnue',
                'description' => 'Bureau utilisé par les secrétaires pour leurs activités quotidiennes.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bureau_secretariat_general.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rallonge/ Secrétariat',

                'marque' => 'YAKI',
                'description' => 'Multiprise électrique pour connecter plusieurs équipements.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/rallonge_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Onduleur',

                'marque' => 'MERCURY',
                'description' => 'Alimentation de secours pour équipements électroniques.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleur_mercury.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Onduleur',

                'marque' => 'EATON',
                'description' => 'Appareil UPS pour la protection de données en cas de coupure.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/onduleur_eaton.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Armoire/Caissons',

                'marque' => 'inconnue',
                'description' => 'Mobilier de rangement avec tiroirs ou portes.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/armoire_caissons.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Brasseurs',

                'marque' => 'SMC',
                'description' => 'Équipement de gestion de câblage dans les baies réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/brasseurs.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chaises/ Secrétariat',

                'marque' => 'inconnue',
                'description' => 'Chaises ergonomiques destinées au personnel administratif.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chaises_secretariat.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chaises/Stagiaires',

                'marque' => 'inconnue',
                'description' => 'Chaises standards fournies pour les stagiaires.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chaises_stagiaires.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tableau Politique de Qualité',

                'marque' => 'inconnue',
                'description' => "Tableau mural affichant la politique de qualité de l'entreprise.",
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/tableau_qualite.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Appareil Photo/Vidéo',

                'marque' => 'Canon',
                'description' => 'Appareil numérique pour prise de photos et vidéos.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/appareil_photo_video.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Répéteur',

                'marque' => 'WPS',
                'description' => 'Appareil permettant d’étendre la portée du signal Wi-Fi.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/repeteur.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chaise à Trois places',

                'marque' => 'inconnue',
                'description' => 'Chaise pouvant accueillir trois personnes.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chaise_trois_places.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Moulu',

                'marque' => 'inconnue',
                'description' => 'Produit moulu (préciser la nature si nécessaire).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/moulu.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Moulu IPS',

                'marque' => 'Ingelec',
                'description' => 'Produit moulu fourni par Ingelec.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/moulu_ips.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone Fixe',

                'marque' => 'Panasonic',
                'description' => 'Téléphone fixe de marque Panasonic.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Batterie Panasonic',

                'marque' => 'Mercury',
                'description' => 'Batterie Panasonic fournie par Mercury.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/batterie_panasonic.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ODF',

                'marque' => 'inconnue',
                'description' => 'Organisateur de fibres optiques (ODF).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/odf.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ONT',

                'marque' => 'HUAWEI',
                'description' => 'Terminal réseau optique (ONT) de marque HUAWEI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ont.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Etiqueteuse',

                'marque' => 'inconnue',
                'description' => 'Appareil pour imprimer des étiquettes.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/etiqueteuse.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DOM',

                'marque' => 'HIKVISION',
                'description' => 'Dispositif de sécurité HIKVISION.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dom_hikvision.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Souffleur',

                'marque' => 'WORXPLEX',
                'description' => 'Souffleur pour le nettoyage extérieur.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/souffleur_worxplex.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rouleau câble Ethernet',

                'marque' => 'inconnue',
                'description' => 'Rouleau de câble réseau Ethernet.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/rouleau_cable_ethernet.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plots',

                'marque' => 'inconnue',
                'description' => 'Plots pour travaux ou marquage.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/plots.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Scie à Métaux',

                'marque' => 'inconnue',
                'description' => 'Scie pour couper le métal.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/scie_a_metaux.jpeg',
                'categorie_id' => 4,
                'quantite' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',

                'marque' => 'GRANDSTREAM',
                'description' => 'Téléphone fixe de marque GRANDSTREAM.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_grandstream.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier HP K-1700',

                'marque' => 'HP',
                'description' => 'Clavier HP modèle K-1700.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_hp_k1700.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier SUN',

                'marque' => 'SUN',
                'description' => 'Clavier de marque SUN.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_sun.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier DELL/L100',

                'marque' => 'DELL',
                'description' => 'Clavier DELL modèle L100.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_dell_l100.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Marteau Piqueur',

                'marque' => 'TITAN',
                'description' => 'Marteau piqueur de marque TITAN.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/marteau_piqueur_titan.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'ONT HUAWEI',

                'marque' => 'HUAWEI',
                'description' => 'Terminal réseau optique HUAWEI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ont_huawei.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'MEDIA Converter',

                'marque' => 'NetPro',
                'description' => 'Convertisseur média NetPro.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/media_converter_netpro.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupleur LC Bleue',

                'marque' => 'inconnue',
                'description' => 'Coupleur LC de couleur bleue.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/coupleur_lc_bleue.jpeg',
                'categorie_id' => 2,
                'quantite' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteur Fibre',

                'marque' => 'inconnue',
                'description' => 'Connecteur pour fibre optique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteur_fibre.jpeg',
                'categorie_id' => 2,
                'quantite' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupleur LC Vert',

                'marque' => 'inconnue',
                'description' => 'Coupleur LC de couleur verte.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/coupleur_lc_vert.jpeg',
                'categorie_id' => 2,
                'quantite' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur Echolife',

                'marque' => 'inconnue',
                'description' => 'Routeur Echolife pour réseau informatique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_echolife.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Fibre Transparente',

                'marque' => 'inconnue',
                'description' => 'Fibre optique transparente.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/fibre_transparente.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boite de Dérivation',

                'marque' => 'inconnue',
                'description' => 'Boite pour dérivation électrique ou fibre optique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/boite_derivation.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Serrures',

                'marque' => 'inconnue',
                'description' => 'Serrures diverses pour portes et meubles.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/serrures.jpeg',
                'categorie_id' => 4,
                'quantite' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Caméra HILOOK',

                'marque' => 'HILOOK',
                'description' => 'Caméra de surveillance HILOOK.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/camera_hilook.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',

                'marque' => 'ALCATEL',
                'description' => 'Téléphone fixe de marque ALCATEL.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_alcatel.jpeg',
                'categorie_id' => 2,
                'quantite' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Sapin de NOEL',

                'marque' => 'inconnue',
                'description' => 'Décoration sapin de Noël.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/sapin_noel.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Imprimante I-SENSYS',

                'marque' => 'inconnue',
                'description' => 'Imprimante I-SENSYS pour bureau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/imprimante_isensys.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Handboss Universal',

                'marque' => 'inconnue',
                'description' => 'Outil Handboss Universal.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/handboss_universal.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Serveur OPTI UPS',

                'marque' => 'inconnue',
                'description' => 'Serveur avec alimentation UPS OPTI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/serveur_opti_ups.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Malette d’équipement',

                'marque' => 'inconnue',
                'description' => 'Malette contenant divers équipements nécessaires.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/malette_equipement.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Embase de Prise RJ45',

                'marque' => 'inconnue',
                'description' => 'Embase pour prise réseau RJ45.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/embase_prise_rj45.jpeg',
                'categorie_id' => 2,
                'quantite' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plaque Frontale',

                'marque' => 'inconnue',
                'description' => 'Plaque frontale pour prise ou équipement.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/plaque_frontale.jpeg',
                'categorie_id' => 2,
                'quantite' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince Optique',

                'marque' => 'inconnue',
                'description' => 'Pince pour manipulation de fibre optique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_optique.jpeg',
                'categorie_id' => 2,
                'quantite' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Testeur RJ45 RJ11',

                'marque' => 'inconnue',
                'description' => 'Testeur pour câbles RJ45 et RJ11.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/testeur_rj45_rj11.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Perceuse T.I.P',

                'marque' => 'inconnue',
                'description' => 'Perceuse électrique T.I.P.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/perceuse_tip.jpg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Multimètre',

                'marque' => 'ING-CO',
                'description' => 'Multimètre de marque ING-CO.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/multimetre_ingco.jpg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câbles Ethernet Pré sertis',

                'marque' => 'inconnue',
                'description' => 'Câbles Ethernet déjà sertis prêts à l’emploi.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cables_ethernet_presertis.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'CUI-PH04',

                'marque' => 'inconnue',
                'description' => 'Produit ou équipement CUI-PH04.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cui_ph04.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier HP KU-0841',

                'marque' => 'HP',
                'description' => 'Clavier modèle HP KU-0841.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_hp_ku0841.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'BNC',

                'marque' => 'inconnue',
                'description' => 'Connecteurs BNC pour câblage.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bnc.jpeg',
                'categorie_id' => 2,
                'quantite' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier HP TPA-L001K Noir',

                'marque' => 'HP',
                'description' => 'Clavier HP TPA-L001K couleur noire.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_hp_tpa_l001k_noir.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Clavier HP TPA-L001K Blanc',

                'marque' => 'HP',
                'description' => 'Clavier HP TPA-L001K couleur blanche.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/clavier_hp_tpa_l001k_blanc.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Unité Centrale DELL',

                'marque' => 'DELL',
                'description' => 'Unité centrale de marque DELL.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/unite_centrale_dell.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Serveur DELL',

                'marque' => 'DELL',
                'description' => 'Serveur informatique de marque DELL.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/serveur_dell.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boucle',

                'marque' => 'inconnue',
                'description' => 'Boucle pour installation électrique ou réseau.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/boucle.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur CISCO',

                'marque' => 'CISCO',
                'description' => 'Routeur réseau CISCO.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_cisco.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe THOSON',

                'marque' => 'THOSON',
                'description' => 'Téléphone fixe de marque THOSON.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_thoson.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Surface BOX',

                'marque' => 'inconnue',
                'description' => 'Surface BOX pour installation technique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/surface_box.jpg',
                'categorie_id' => 2,
                'quantite' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone fixe',

                'marque' => 'Panasonic',
                'description' => 'Téléphone fixe Panasonic.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_fixe_panasonic.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Testeur Câbles Ethernet',

                'marque' => 'NOYAFA',
                'description' => 'Testeur de câbles Ethernet de marque NOYAFA.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/testeur_cables_ethernet_noyafa.jpg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DVR',

                'marque' => 'HIKVISION',
                'description' => 'Enregistreur vidéo numérique HIKVISION.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dvr_hikvision.jpg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'DVR',

                'marque' => 'AUSNO',
                'description' => 'Enregistreur vidéo numérique AUSNO.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/dvr_ausno.jpg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Détecteur Incendie',

                'marque' => 'inconnue',
                'description' => 'Détecteur d’incendie pour sécurité.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/detecteur_incendie.jpeg',
                'categorie_id' => 4,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Téléphone/PBX',

                'marque' => 'inconnue',
                'description' => 'Système téléphonique PBX.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/telephone_pbx.jpeg',
                'categorie_id' => 5,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Colle Bougie',

                'marque' => 'inconnue',
                'description' => 'Colle spéciale pour bougies.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/colle_bougie.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Fer à Souder',

                'marque' => 'inconnue',
                'description' => 'Fer à souder pour travaux électroniques.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/fer_a_souder.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Ecrou & Boulons',

                'marque' => 'inconnue',
                'description' => 'Jeu d’écrous et boulons divers.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/ecrou_boulons.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Vis & Chevilles',

                'marque' => 'inconnue',
                'description' => 'Vis et chevilles pour fixation.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/vis_chevilles.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Sacs d’emballage',

                'marque' => 'inconnue',
                'description' => 'Sacs pour emballage et stockage.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/sacs_emballage.jpeg',
                'categorie_id' => 2,
                'quantite' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boite d’Alimentation :CD 12V',

                'marque' => 'inconnue',
                'description' => 'Boite d’alimentation 12V CD.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/boite_alimentation_12v.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'PABX TC-3000K IKE',

                'marque' => 'inconnue',
                'description' => 'Système PABX TC-3000K de marque IKE.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pabx_tc3000k_ike.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'LaserJet PH /CI115A',

                'marque' => 'inconnue',
                'description' => 'Imprimante LaserJet modèle PH/CI115A.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/laserjet_ph_ci115a.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Boulons C11015',

                'marque' => 'inconnue',
                'description' => 'Boulons modèle C11015.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/boulons_c11015.jpeg',
                'categorie_id' => 2,
                'quantite' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chargeurs',

                'marque' => 'inconnue',
                'description' => 'Chargeurs divers pour appareils électroniques.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chargeurs.jpeg',
                'categorie_id' => 1,
                'quantite' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chargeurs Android',

                'marque' => 'inconnue',
                'description' => 'Chargeurs compatibles Android.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chargeurs_android.jpeg',
                'categorie_id' => 1,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tie',

                'marque' => 'inconnue',
                'description' => 'Serre-câbles (Tie) pour gestion des câbles.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/tie.jpeg',
                'categorie_id' => 2,
                'quantite' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince à Sertir Bleue',

                'marque' => 'inconnue',
                'description' => 'Pince à sertir de couleur bleue.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_a_sertir_bleue.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pince à Sertir Verte',

                'marque' => 'inconnue',
                'description' => 'Pince à sertir de couleur verte.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/pince_a_sertir_verte.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Interrupteur YAKI',

                'marque' => 'inconnue',
                'description' => 'Interrupteur de marque YAKI.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/interrupteur_yaki.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Routeur D-Link',

                'marque' => 'D-Link',
                'description' => 'Routeur réseau de marque D-Link.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/routeur_dlink.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Switch HIKVISION',

                'marque' => 'HIKVISION',
                'description' => 'Switch réseau HIKVISION.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/switch_hikvision.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bande de Signalisation/Délimiteur',

                'marque' => 'inconnue',
                'description' => 'Bande pour signalisation et délimitation.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bande_signalisation.jpeg',
                'categorie_id' => 4,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Poulie',

                'marque' => 'inconnue',
                'description' => 'Poulie pour levage ou guidage.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/poulie.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'TvBOX MKQPR',

                'marque' => 'inconnue',
                'description' => 'Boite ou produit TVBOX MKQPR.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/tvbox_mkqpr.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur HDD 1TO',

                'marque' => 'inconnue',
                'description' => 'Disque dur HDD de 1 To.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_hdd_1to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Prolongateur HDMI RX',

                'marque' => 'inconnue',
                'description' => 'Prolongateur HDMI RX pour transmission vidéo.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/prolongateur_hdmi_rx.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Power Bank',

                'marque' => 'inconnue',
                'description' => 'Batterie externe portable (Power Bank).',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/power_bank.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteurs BNC',

                'marque' => 'inconnue',
                'description' => 'Connecteurs BNC pour câblage vidéo.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteurs_bnc.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connecteur RJ45',

                'marque' => 'inconnue',
                'description' => 'Connecteur réseau RJ45.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connecteur_rj45.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble Coaxial UTP',

                'marque' => 'inconnue',
                'description' => 'Câble coaxial UTP pour transmission de données.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_coaxial_utp.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Fiche d’Alimentation',

                'marque' => 'inconnue',
                'description' => 'Fiche d’alimentation électrique.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/fiche_alimentation.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Papier Thermal',

                'marque' => 'inconnue',
                'description' => 'Papier thermique pour imprimantes.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/papier_thermal.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble BNC',

                'marque' => 'inconnue',
                'description' => 'Câble avec connecteur BNC.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_bnc.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur SATA 1TO',

                'marque' => 'TOSHIBA',
                'description' => 'Disque dur SATA 1 To de marque TOSHIBA.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_sata_toshiba.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur SAS 2 TO',

                'marque' => 'inconnue',
                'description' => 'Disque dur SAS de 2 To.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_sas_2to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Disque Dur Pipeline HD 2 TO',

                'marque' => 'inconnue',
                'description' => 'Disque dur Pipeline HD de 2 To.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/disque_dur_pipeline_hd_2to.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Caméra EncroVision',

                'marque' => 'inconnue',
                'description' => 'Caméra de marque EncroVision.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/camera_encrovision.jpeg',
                'categorie_id' => 4,
                'quantite' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Connect Assessories',

                'marque' => 'inconnue',
                'description' => 'Accessoires divers de connexion.',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/connect_assessories.jpeg',
                'categorie_id' => 2,
                'quantite' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble 350.024.373',

                'marque' => 'inconnue',
                'description' => 'Câble référence 350.024.373',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_350_024_373.jpeg',
                'categorie_id' => 2,
                'quantite' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble 350.024.336',

                'marque' => 'inconnue',
                'description' => 'Câble référence 350.024.336',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_350_024_336.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Câble (CLIP)',

                'marque' => 'inconnue',
                'description' => 'Câble type CLIP',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/cable_clip.jpeg',
                'categorie_id' => 2,
                'quantite' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Armement',

                'marque' => 'inconnue',
                'description' => 'Equipement armement',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/armement.jpeg',
                'categorie_id' => 2,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Chaise1 DT',

                'marque' => 'inconnue',
                'description' => 'Chaise pour DT',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/chaise1_dt.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Traverses',

                'marque' => 'inconnue',
                'description' => 'Traverses diverses',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/traverses.jpeg',
                'categorie_id' => 2,
                'quantite' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Trépied/Stabilisateur YF-3388',

                'marque' => 'inconnue',
                'description' => 'Trépied/Stabilisateur modèle YF-3388',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/trepied_stabilisateur_yf_3388.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Climatiseur',

                'marque' => 'Hisense',
                'description' => 'Climatiseur de marque Hisense',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/climatiseur_hisense.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bureau DT',

                'marque' => 'inconnue',
                'description' => 'Bureau pour DT',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/bureau_dt.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rallonge',

                'marque' => 'Ingelec',
                'description' => 'Rallonge électrique de marque Ingelec',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/rallonge_ingelect.jpeg',
                'categorie_id' => 1,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Caisson/Armoire/DT',

                'marque' => 'inconnue',
                'description' => 'Caisson ou armoire pour DT',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/caisson_armeoire_dt.jpeg',
                'categorie_id' => 8,
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Échelle rouge',

                'marque' => 'inconnue',
                'description' => 'Échelle en aluminium ou métal peint en rouge, utilisée pour les accès en hauteur',
                'date_acquisition' => '2025-01-01',
                'image_path' => 'images/echelle_rouge.jpeg',
                'categorie_id' => 8, // adapte l'ID si nécessaire
                'quantite' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
