# Forcer PHP avec l'extension GD (nécessaire pour DomPDF)
[phases.setup]
nixPkgs = ['php82', 'php82Packages.gd']

# Phase d'installation (dépendances backend et frontend)
[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install",
  "npm run build"
]

# Phase de build (optimisation Laravel + migrations)
[phases.build]
cmds = [
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]
