name: Laravel CI

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - run: composer install --no-progress

      # 🔍 Qualité code
      - run: ./vendor/bin/pint --test
      - run: ./vendor/bin/rector process --dry-run

      # 🧪 Tests (TRÈS important)
      - run: php artisan test
